### ISSUE TITLE
GPU support

### ISSUE THREAD

**Issue by ankithadas** [rmrsk/EBGeometry#71]
Dear Robert, 

Out of curiosity, is it possible to convert this library to run on GPUs? Is this something you're interested in or currently working on? 

Kind regards,
Ankith

**Comment by rmrsk** [comment]
Hi Ankith - GPU ports is something that is planned, but I'm currently overbooked at work so it's not something that has taken priority (yet). 

If you have time to help, I would be happy to explain how things are implemented!

**Comment by ankithadas** [comment]
Definitely happy to help. Have you given much thought to this? If so, what do you think should be tackled first?

I should mention that I'm not very familiar with computational geometry, but I'm comfortable with C++.

**Comment by rmrsk** [comment]
Great!

First, we're not interested in distributed geometries so they are therefore replicated across MPI ranks. The common use case is therefore that each rank owns the whole geometry, and that CPU/GPU query the distance field. So that simplifies things since we don't care about parallel BVH construction or traversal. 

My strategy was to get started by taking the analytic distance fields and placing them on the GPU. Once that is done, the next step is to put the BVHs on the GPU, and validate the BVH code with standard CSG operations (e.g., unions). As a last step, because polygon meshes are treated similar to analytic distance fields, porting the DCEL code to the GPU would be done last.

I want to point out that I'm not really interested in AMReX-only capabilities. For example, EBGeometry uses templated precision to reduce memory consumption for large meshes. We also use this code with Chombo and other, private AMR codes.

**Comment by ankithadas** [comment]
That sounds good, and most of my objectives align with yours. After reviewing the code more carefully, I am unsure how we can move the current implementation to GPUs while preserving the same code structure (i.e., polymorphic classes). Implementing virtual functions in device code presents challenges and would involve some complex semantics (refer [Is There Any Way To Copy vtable From Host To Device](https://stackoverflow.com/questions/63378891/is-there-any-way-to-copy-vtable-from-host-to-device-cuda-c) and [How to implement device side CUDA virtual functions?](https://stackoverflow.com/questions/26812913/how-to-implement-device-side-cuda-virtual-functions)). 

If polymorphic classes are not essential, we could explore some ideas from AMReX's approach.

**Comment by rmrsk** [comment]
Yes, a GPU port would probably involve a complete rewrite.

**Comment by rmrsk** [comment]
Hi again Ankith,

Just letting you know that I've started exploring designs for a GPU port, but will need some time to flesh out a proper interface. In the absence of copyable polymorphism we'll either have to do everything on the host/GPU, with no allowed copies from host to GPU. Or we can leave out polymorphic classes altogether, in which case things like CSG unions must be done through variadic templates (like in AMReX). However, I want to be able to use CSG unions with many different types of objects (tens/hundreds), and I'm a bit reluctant to require that users maintain a large number of vectors of different types of implicit functions.

Perhaps you have some other ideas?

**Comment by rmrsk** [comment]
One can construct the functions on the GPU and keep the vtable there. One would have to do the same on the host, and thus carry around separate copies of the geometries both host and device. This functionality will probably require some easy-to-break infrastructure that has to be carefully designed to prevent misuse. I also haven't checked how AMReX does things, and in particular whether or not they demand a proper copy from host to device (although that is probably something that can be interfaced by minor changes in AMReX). 

The following code works for me with CUDA (I have not checked with HIP). 

```
#include <cstdio>
#include "cuda.h"

class ImplicitFunction {
public:
  __host__ __device__
  ImplicitFunction(){
  }
  
  __host__ __device__
  virtual void value() = 0;
};

class Sphere : public ImplicitFunction {
public:
  __host__ __device__
  void value() override {
    printf("sphere = 1\n");
  }
};

class Cylinder : public ImplicitFunction {
public:
  __host__ __device__
  void value() override {
    printf("cylinder = 2\n");
  }
};

template <typename T>
__global__
void makeImplicitFunction(ImplicitFunction** func)
{
  (*func) = new T();

  (*func)->value();
}

__global__
void callValueFunction(ImplicitFunction** func)
{
  (*func)->value();
}

int main()
{
  ImplicitFunction** sphere;
  ImplicitFunction** cylinder;

  cudaMalloc((void**) &sphere, sizeof(Sphere**));
  cudaMalloc((void**) &cylinder, sizeof(Cylinder**));

  // Create implicit functions
  printf("When making implicit functions on GPU\n--------\n");
  makeImplicitFunction<Sphere><<<1,1>>>(sphere);
  makeImplicitFunction<Cylinder><<<1,1>>>(cylinder);
  cudaDeviceSynchronize();

  // Call the value functions
  printf("\n When calling value function on GPU\n--------\n");
  callValueFunction<<<1,1>>>(sphere);
  callValueFunction<<<1,1>>>(cylinder);
  cudaDeviceSynchronize();
  
  return 0;
}
```

**Comment by ankithadas** [comment]
Hey Rober, 

Sorry for the late reply. I got bogged down with other work...

I was thinking of something along these lines 

```
#include <cstdio>
#include <cuda.h>

template<typename T>
__global__ 
void constructOnDevice(void *other) {
  T temp =  T(*static_cast<T*>(other));
  memcpy(other, &temp, sizeof(T));
}

class ImplicitFunction {
public:
  __host__ __device__
  ImplicitFunction(){
  }
  
  __host__ __device__
  virtual void value() = 0;

  __host__ 
  virtual void moveToDevice(void* device_ptr) = 0;
};

class Sphere : public ImplicitFunction {
public:
  __host__ __device__
  void value() override {
    printf("sphere = %d\n", data);
  }

  int data = 1;

  void moveToDevice(void* device_ptr) override {
    cudaMemcpy(device_ptr, this, sizeof(Sphere), cudaMemcpyHostToDevice);
    constructOnDevice<Sphere><<<1,1>>>(device_ptr);
  }
};

class Cylinder : public ImplicitFunction {
public:
  __host__ __device__
  Cylinder() : data(0) {}
  __host__ __device__
  Cylinder(int data) : data(data) {}

  __host__ __device__
  void value() override {
    printf("cylinder = %d\n", data);
  }

  int data = 2;

  void moveToDevice(void* device_ptr) override {
    cudaMemcpy(device_ptr, this, sizeof(Cylinder), cudaMemcpyHostToDevice);
    constructOnDevice<Cylinder><<<1,1>>>(device_ptr);
  }
};

__global__
void callValueFunction(ImplicitFunction* func)
{
  func->value();
}

int main()
{
  ImplicitFunction* h_sphere;
  ImplicitFunction* h_cylinder;

  h_sphere = new Sphere();
  h_cylinder = new Cylinder(5);

  ImplicitFunction* d_sphere;
  ImplicitFunction* d_cylinder;

  cudaMalloc(&d_sphere, sizeof(Sphere));
  cudaMalloc(&d_cylinder, sizeof(Cylinder));

  h_sphere->moveToDevice(d_sphere);
  h_cylinder->moveToDevice(d_cylinder);

  cudaDeviceSynchronize();

  // Call the value functions
  printf("\n When calling value function on GPU\n--------\n");
  callValueFunction<<<1,1>>>(d_sphere);
  callValueFunction<<<1,1>>>(d_cylinder);
  cudaDeviceSynchronize();

  cudaFree(d_sphere);
  cudaFree(d_cylinder);

  delete h_sphere;
  delete h_cylinder;
  
  return 0;
}
```

The major difference is the lack of double pointers. However, this approach is a bit sketchy

Kind regards,
Ankith

**Comment by rmrsk** [comment]
Hi Ankith,

I have a development version of EBGeometry that you can take a look at - will send you a repo invite. I will most likely use a factory pattern for constructing implicit functions. The reason for that is if you have a CSG union that took host pointers then the moveToDevice function will need to construct the device-side functions, but those should be constructed externally and passed by pointer. Other than that, I think that polymorphic behavior is achievable although I still don't know what kind of vtable penalty we get on the GPU.

**Comment by rmrsk** [comment]
Closing this issue since the discussion is best moved elsewhere.
